cargo.add.features.description=Lista de funcionalidades separadas por espacios o comas a activar para esta dependencia
cargo.all-features.description=Activa todas las funciones disponibles de todos los paquetes seleccionados
cargo.bench.bench.description=Ejecutar pruebas de rendimiento para los benchmarks especificados
cargo.bench.benches.description=Ejecuta las pruebas de rendimiento de todos los objetivos que tengan el flag bench = true en el manifiesto en modo benchmark
cargo.bench.package.description=Ejecutar pruebas de rendimiento solo para el paquete especificado
cargo.bench.target.description=Realizar pruebas de rendimiento para la arquitectura especificada
cargo.bench.test.description=Ejecutar benchmarks de las pruebas de integración especificadas
cargo.build.package.description=Construir solo el paquete especificado
cargo.check.bench.description=Comprobar el benchmark especificado
cargo.check.benches.description=Comprueba todos los objetivos que tengan el flag de manifiesto bench = true en modo benchmark
cargo.check.bin.description=Comprobar el binario especificado
cargo.check.example.description=Comprobar el ejemplo especificado
cargo.check.package.description=Comprobar solo el paquete especificado
cargo.check.target.description=Verificar la arquitectura especificada
cargo.check.test.description=Comprobar la prueba de integración especificada
cargo.clean.package.description=Limpia solo los paquetes especificados
cargo.clean.target.description=Limpiar la arquitectura especificada
cargo.doc.bin.description=Documentar el binario especificado
cargo.doc.lib.description=Documentar la biblioteca del paquete
cargo.doc.package.description=Documentar solo los paquetes especificados
cargo.doc.release.description=Documentar los artefactos optimizados utilizando el perfil release
cargo.doc.target.description=Documentar la arquitectura especificada
cargo.doc.workspace.description=Documentar todos los miembros del espacio de trabajo
cargo.exclude.description=Excluir los paquetes especificados
cargo.features.description=Lista de funcionalidades separadas por espacios o comas para activar
cargo.fetch.target.description=Obtener la arquitectura especificada
cargo.fix.all-targets.description=Corregir todos los objetivos
cargo.fix.allow-dirty.description=Corregir el código incluso si el directorio de trabajo tiene cambios
cargo.fix.allow-no-vcs.description=Corregir el código incluso si no se detecta un VCS
cargo.fix.allow-staged.description=Corregir el código incluso si el directorio de trabajo tiene cambios preparados (staged)
cargo.fix.bench.description=Corregir los benchmarks especificados
cargo.fix.benches.description=Corregir todos los objetivos que tengan la bandera de manifiesto bench = true en modo benchmark
cargo.fix.bin.description=Corregir el binario especificado
cargo.fix.bins.description=Corregir todos los objetivos binarios
cargo.fix.broken-code.description=Corregir incluso si el código ya tiene errores de compilación
cargo.fix.description=Corregir automáticamente las advertencias de lint reportadas por rustc
cargo.fix.example.description=Corregir el ejemplo especificado
cargo.fix.examples.description=Corregir todos los objetivos de ejemplo
cargo.fix.lib.description=Corregir la biblioteca del paquete
cargo.fix.package.description=Corregir solo el paquete especificado
cargo.fix.profile.description=Cambiar el comportamiento de corrección
cargo.fix.release.description=Corregir artefactos optimizados usando el perfil de release
cargo.fix.target.description=Realiza correcciones para un objetivo determinado
cargo.fix.test.description=Corrige la prueba de integración especificada
cargo.fix.tests.description=Corrige todos los objetivos en modo de prueba que tienen establecido el indicador de manifiesto test = true
cargo.fix.workspace.description=Corregir todos los miembros del espacio de trabajo
cargo.frozen.description=Fuerza a Cargo a utilizar el archivo Cargo.lock empaquetado (si está disponible) y evita realizar actualizaciones desde la red.
cargo.init.registry.description=Esto establecerá el campo publish en Cargo.toml con el nombre del registro proporcionado, lo que limitará la publicación únicamente a dicho registro.
cargo.init.vcs.description=Inicializa un nuevo repositorio de VCS para el sistema de control de versiones especificado (git, hg, pijul o fossil), o no inicializa ningún control de versiones (none)
cargo.install.bin.description=Instalar solo el binario especificado
cargo.install.example.description=Instalar solo el ejemplo especificado
cargo.install.no-track.description=Por defecto, Cargo utiliza archivos de metadatos almacenados en el directorio raíz de instalación para realizar un seguimiento de los paquetes instalados.
cargo.install.root.description=Directorio donde se instalarán los paquetes
cargo.install.target.description=Instalar para la arquitectura proporcionada
cargo.locked.description=Fuerza a Cargo a usar el archivo Cargo.lock empaquetado si está disponible
cargo.new.registry.description=Esto establecerá el campo publish en Cargo.toml con el nombre del registro proporcionado, lo que restringirá la publicación únicamente a ese registro.
cargo.new.vcs.description=Inicializa un nuevo repositorio VCS para el sistema de control de versiones especificado (git, hg, pijul o fossil) o no inicializa ningún control de versiones (none)
cargo.owner.add.description=Invitar a un usuario o equipo determinado como propietario
cargo.package-option.description=Empaqueta los paquetes locales en un archivo tar distribuible
cargo.publish.target.description=Publicar para la arquitectura especificada
cargo.quiet.description=No mostrar salida en stdout
cargo.run.bin.description=Ejecutar el binario especificado
cargo.run.example.description=Ejecutar el ejemplo especificado
cargo.run.target.description=Ejecutar para la arquitectura dada
cargo.rustc.bench.description=Construye el benchmark especificado
cargo.rustc.benches.description=Construye todos los objetivos que tienen establecida la marca de manifiesto bench = true en modo benchmark
cargo.rustc.bin.description=Construir el binario especificado
cargo.rustc.example.description=Compilar el ejemplo especificado
cargo.rustc.target.description=Compilar para una arquitectura determinada
cargo.rustc.test.description=Construir la prueba de integración especificada
cargo.rustdoc.bench.description=Documentar los benchmarks especificados
cargo.rustdoc.benches.description=Documenta todos los targets que tienen el flag de manifiesto bench = true establecido en el modo benchmark
cargo.rustdoc.bin.description=Documentar el binario especificado
cargo.rustdoc.bins.description=Documentar todos los objetivos binarios
cargo.rustdoc.example.description=Documentar el ejemplo especificado
cargo.rustdoc.examples.description=Documentar todos los objetivos de ejemplo
cargo.rustdoc.lib.description=Documentar la biblioteca del paquete
cargo.rustdoc.release.description=Documentar artefactos optimizados usando el perfil de release
cargo.rustdoc.target.description=Documentar la arquitectura especificada
cargo.rustdoc.test.description=Documentar la prueba de integración especificada
cargo.rustdoc.tests.description=Documenta todos los objetivos que tienen el flag de manifiesto test = true activado en el modo de prueba
cargo.set-version.bump.description=Incrementa el número de versión mediante major, minor o patch
cargo.set-version.workspace.description=Modificar todos los miembros del espacio de trabajo
cargo.test.bench.description=Probar los benchmarks especificados
cargo.test.benches.description=Prueba todos los objetivos con el flag de manifiesto bench = true establecido en modo benchmark
cargo.test.bin.description=Probar el binario especificado
cargo.test.example.description=Probar el ejemplo especificado
cargo.test.package.description=Probar solo el paquete especificado
cargo.test.target.description=Probar la arquitectura especificada
cargo.test.test.description=Probar una prueba de integración específica
cargo.tree.edges.description=Tipos de dependencias que se mostrarán
cargo.tree.no-dedupe.description=No eliminar duplicados de las dependencias repetidas
cargo.tree.package.description=Mostrar solo los paquetes especificados
cargo.tree.target.description=Filtrar las dependencias que coincidan con el triple de destino dado
cargo.update.package.description=Actualizar solo los paquetes especificados
cargo.update.precise.description=Cuando se utiliza con -p, permite especificar el número de versión exacto al que se desea establecer el paquete.
cargo.upgrade.package.description=Actualizar solo los paquetes especificados
cargo.upgrade.precise.description=Especifica la versión exacta a la que se debe establecer la dependencia
cargo.vendor.description=Almacenar todas las dependencias localmente
cargo.vendor.sync.description=Especifica manifiestos Cargo.toml adicionales para el espacio de trabajo que también deben almacenarse localmente y sincronizarse con la salida
cargo.vendor.versioned-dirs.description=La adición de versiones se suele realizar solo para distinguir entre múltiples versiones del mismo paquete.