static.plugin.id=com.alibabacloud.intellij.cosy
static.plugin.name=Lingma - Asistente de codificación con IA de Alibaba Cloud
vpc.enabled=false
## \u7528\u4E8E\u533A\u5206lingma client\u4E0E\u6807\u51C6\u7248\u7684\u8BF7\u6C42
plugin.publisher=aliyun
plugin.name=Lingma
product=lingma